name: agones
description: gRPC generated client for Agones - a library for hosting, running and scaling 
  dedicated game servers on Kubernetes.
version: 1.28.0
homepage: https://markvideon.dev
environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  collection: ^1.17.0
  fixnum: ^1.0.1
  grpc: ^3.1.0
  protobuf: ^2.1.0
